# Generated by Django 4.1.1 on 2022-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=24)),
                ('switches', models.CharField(max_length=24)),
                ('keycaps', models.CharField(max_length=24)),
                ('stabilizers', models.CharField(max_length=24)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=24)),
            ],
        ),
    ]
